question_data = [{"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "The Republic of Malta is the smallest microstate worldwide.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Nutella is produced by the German company Ferrero.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Donkey Kong was originally set to be a Popeye arcade game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question":
                      "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "type": "boolean", "difficulty": "easy",
                  "question":
                      "The anime &quot;Lucky Star&quot; follows the story of one girl who is unaware she is God.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "easy", "question": "Salt is 100% composed of Sodium.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The color orange is named after the fruit.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question":
                      "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "type": "boolean", "difficulty": "easy",
                  "question": "In Pok&eacute;mon, Ash&#039;s Pikachu refuses to go into a pokeball.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question":
                      "In the game Dead by Daylight, the killer Michael Myers is refered to as &quot;The Shape&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "The names of Tom Nook&#039;s cousins in the Animal Crossing franchise are named &quot;Timmy&quot; and &quot;Jimmy&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Kublai Khan is the grandchild of Genghis Khan?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Celebrities", "type": "boolean", "difficulty": "easy",
                  "question": "Tupac Shakur died due to complications from being stabbed in 1996.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final chapter of the game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
